@startuml
class MyString {
  - char* data
  - int length

  + MyString()
  + MyString(const char* str)
  + MyString(const MyString& other)
  + ~MyString()

  + operator=(const MyString& other) : MyString&
  + operator[](int index) : char&
  + operator[](int index) const : const char&
  + operator()(int start, int len) const : MyString

  + operator>(const MyString& other) const : bool
  + operator<(const MyString& other) const : bool
  + operator==(const MyString& other) const : bool

  + operator+(const MyString& other) const : MyString
  + operator+(const char* str) const : MyString
  + operator+(char c) const : MyString
  + operator+=(const MyString& other) : MyString&

  + operator++() : MyString&
  + operator++(int) : MyString
  + operator--() : MyString&
  + operator--(int) : MyString

  + size() const : int

  + operator<<(ostream& os, const MyString& str) : ostream&
  + operator>>(istream& is, MyString& str) : istream&
}

MyString "1" <.. "friend operator+"
@enduml
